#!/bin/bash
# Generates the lock files of gfae_ubuntu24.def from the specifications in this directory:
# - base_env.yml                   -> base_env.conda.lock             (conda base environment)
# - nighres_build_py3XX (in here)  -> nighres_build_py3XX.conda.lock  (build environments for the nighres wheels)
# - nighres_jdk (in here)          -> nighres_jdk.conda.lock          (Java runtime of nighres)
# - base_env.pip.txt               -> base_env.pip.lock               (pip packages of the base environment)
# Conda lock files are in conda's explicit format (exact package URLs with sha256), installed without solving.
#
# Run on any linux-64 machine with internet access; it solves into temporary environments in a work directory
# (default: a new directory under /tmp; several GB):
#   ./make_locks.sh [work_dir]
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
work=${1:-$(mktemp -d)}
mkdir -p ${work}
export MAMBA_ROOT_PREFIX=${work}/mamba
# solve for the glibc of Ubuntu 24.04, independent of the machine running this script
export CONDA_OVERRIDE_GLIBC=2.39

# micromamba (pinned)
micromamba=${work}/micromamba
curl -fsSL --retry 5 -o ${micromamba} \
    https://github.com/mamba-org/micromamba-releases/releases/download/2.9.0-0/micromamba-linux-64
echo "$(sed -n 's/^micromamba-linux-64 2.9.0-0 sha256 //p' ${here}/make_locks.sha256)  ${micromamba}" | sha256sum -c --quiet -
chmod +x ${micromamba}

solve() {  # solve <name> <micromamba create arguments...>
    local name=$1; shift
    rm -rf ${work}/${name}
    ${micromamba} create -y -q -p ${work}/${name} --override-channels -c conda-forge "$@"
}

# conda base environment (its conda exports all lock files, with sha256)
solve base -f ${here}/base_env.yml
conda=${work}/base/bin/conda
export_lock() {  # export_lock <name>
    {
        echo "# generated by make_locks.sh on $(date -u +%Y-%m-%d) from the specifications in $(basename ${here})/"
        ${conda} list -p ${work}/$1 --explicit --sha256
    } > ${here}/$1.conda.lock
    echo "$1: $(grep -c '^https' ${here}/$1.conda.lock) packages"
}
export_lock base
mv ${here}/base.conda.lock ${here}/base_env.conda.lock

# nighres: build environments (python + JCC, which brings OpenJDK 8) and the runtime JDK
for py in 3.11 3.12 3.13; do
    name=nighres_build_py${py/./}
    solve ${name} "python=${py}" jcc setuptools wheel pip
    export_lock ${name}
done
solve nighres_jdk "openjdk=8"
export_lock nighres_jdk

# pip packages of the base environment (installed without dependencies, which are in the conda lock), with hashes
rm -rf ${work}/pip && mkdir -p ${work}/pip
${work}/base/bin/python -m pip download -q --no-deps --only-binary=:all: -d ${work}/pip -r ${here}/base_env.pip.txt
{
    echo "# generated by make_locks.sh on $(date -u +%Y-%m-%d) from base_env.pip.txt; install with"
    echo "# pip install --no-deps --require-hashes -r base_env.pip.lock"
    grep -v '^#' ${here}/base_env.pip.txt | grep -v '^$' | while read -r req; do
        name=${req%%==*}
        file=$(ls ${work}/pip | grep -i "^${name//-/[-_]}-" | head -n 1)
        echo "${req} --hash=sha256:$(sha256sum ${work}/pip/${file} | cut -d' ' -f1)"
    done
} > ${here}/base_env.pip.lock
cat ${here}/base_env.pip.lock
