#!/usr/bin/env python3
"""
Generates the version pins of the conda base environment of gfae_ubuntu22.def and gfae_matlab_ubuntu22.def from
the conda base environment of an existing gfae container (here gfae_20240902T132553Z, the last image in which
ciftify works: python 3.11.9, nibabel 3.2.2).

The complete base environment is pinned:
- base_env_conda_pins.txt: all conda packages as name==version=build (install with conda install --file)
- base_env_pip_pins.txt:   all packages installed by pip as name==version (install with pip install --no-deps -r),
                           including packages with which pip replaced a conda package (e.g. traits); packages
                           installed by pip from a local directory (nighres, gradunwarp) are left out, they are
                           built from source by the definition file

Run with the base python of that container, e.g.:
  apptainer exec gfae_20240902T132553Z_....sif /opt/conda/bin/python make_base_env_pins.py <output_dir>
"""

import sys
import os
import re
import json
import glob
import importlib.metadata as metadata

out_dir = sys.argv[1] if len(sys.argv) > 1 else '.'
conda_meta_dir = os.path.join(sys.prefix, 'conda-meta')
source = os.environ.get('GFAE_PIN_SOURCE', 'gfae_20240902T132553Z')


def normalize(name):
    return re.sub(r'[-_.]+', '-', name).lower()


conda_packages = {}
for fname in glob.glob(os.path.join(conda_meta_dir, '*.json')):
    with open(fname) as f:
        record = json.load(f)
    conda_packages[record['name']] = record

pip_packages = {}
local_packages = {}
for dist in metadata.distributions():
    if (dist.read_text('INSTALLER') or '').strip() != 'pip':
        continue
    name = normalize(dist.metadata['Name'])
    direct_url = json.loads(dist.read_text('direct_url.json') or '{}')
    if direct_url.get('url', '').startswith('file:'):
        local_packages[name] = dist.version
    else:
        pip_packages[name] = dist.version

with open(os.path.join(out_dir, 'base_env_conda_pins.txt'), 'w') as f:
    print('# conda base environment of gfae, pinned to the versions of the base environment of', file=f)
    print(f'# {source} (generated by make_base_env_pins.py); install with conda install --file', file=f)
    for name in sorted(conda_packages):
        record = conda_packages[name]
        print(f"{name}=={record['version']}={record['build']}", file=f)

with open(os.path.join(out_dir, 'base_env_pip_pins.txt'), 'w') as f:
    print('# pip packages of the conda base environment of gfae, pinned to the versions of', file=f)
    print(f'# {source} (generated by make_base_env_pins.py); install with pip install --no-deps -r', file=f)
    print(f"# (built from source by the definition file: {', '.join(f'{n} {v}' for n, v in sorted(local_packages.items()))})",
          file=f)
    for name, version in sorted(pip_packages.items()):
        print(f'{name}=={version}', file=f)

print(f'{len(conda_packages)} conda packages, {len(pip_packages)} pip packages, '
      f'not pinned (local): {sorted(local_packages)}')
